### ISSUE TITLE
sAmaveda svara support?

### ISSUE THREAD

**Issue by vvasuki** [deepestblue/sampradaya#41] opened 2021-07-26 02:16 UTC
No idea how sAmavedic svara-s were traditionally marked in grantha. Is it supported?

How would the following, appropriately transliterated, look in grantha with this font?

अ꣢ग्न꣣ आ꣡ या꣢हि वी꣣त꣡ये꣢ गृणा꣣नो꣢ ह꣣व्य꣡दा꣢तये। नि꣡ होता꣢꣯ सत्सि ब꣣र्हि꣡षि꣢ ॥ 1 ॥  
त्व꣡म꣢ग्ने य꣣ज्ञा꣢ना꣣ꣳ हो꣢ता꣣ वि꣡ श्वे꣢षाꣳ हि꣣तः꣢। दे꣣वे꣢भि꣣र्मा꣡नु꣢षे꣣ ज꣡ने꣢ ॥ 2 ॥

**Comment by deepestblue** [comment] 2021-07-28 03:43
Thanks for the test case; Sampradaya did have "support" for Samavedic accents, but TBH, I know little about them, so your test case helped me fix a couple of minor bugs (pushed to repo).

With those fixes, here's the rendering:

![053](https://user-images.githubusercontent.com/5531915/127259161-02c7b0ee-76e9-41d9-8c14-b7105bec4040.png)
![054](https://user-images.githubusercontent.com/5531915/127259170-3cdd29b8-926d-4936-a54f-4a6703a10706.png)

As you can see, there are still a couple of things to fix:

* The accent marks should be over the consonant symbol, even if they appear in the string after any vowel marks/ayogavaha-s etc. I've filed #42 to fix this; the fix is straightforward but a bit tedious because of lack of OS support.
* It looks like Grantha doesn't yet have a codepoint for the `vaidikaa saamasvara ra`, which is at U+A8EF `COMBINING DEVANAGARI LETTER RA` in Devanagari, so I had to take it out of the test string. If you know more about the usage of this accent mark or any proposals to encode it in Grantha, please let me know.

**Comment by vvasuki** [comment] 2021-07-28 04:00
@jamadagni @sridatta1 - any inputs?  

(Very tangentially related - https://github.com/googlefonts/noto-fonts/issues/2086 )

**Comment by jamadagni** [comment] 2021-07-28 08:39
Please see p 13 and following of [my Grantha proposal](https://www.unicode.org/L2/L2009/09372-grantha.pdf) for a description of Sama Vedic notation in Grantha.

The letter RA is not used as a svara marker in Grantha and the purpose is served by the zero above.

**Comment by deepestblue** [comment] 2021-07-29 05:25
Thanks, @jamadagni for the page reference. I went through it and opened #44 to track adding more Samavedic accent marks like the superscript caret and dash.

One question for you. Is the Grantha equivalent of the Devanagari ```नि꣡ होता꣢꣯``` ```𑌨𑌿𑍧 𑌹𑍋𑌤𑌾𑍨𑍦```.  Specifically, after the `tā`,  will there be both a superscript 2 and a superscript 0, to account for the Devanagari superscript 2 and the Devanagari superscript `ra`?

**Comment by jamadagni** [comment] 2021-07-30 06:42
![WhatsApp Image 2021-07-29 at 12 50 05](https://user-images.githubusercontent.com/948170/127611885-d4ef88a6-a620-4594-8490-f7240cdf9c41.png)

**Comment by deepestblue** [comment] 2021-10-31 01:52
Closing as dupe of other issues split out from this

**Closed by deepestblue** 2021-10-31 01:52 UTC

**Comment by deepestblue** [comment] 2022-01-03 10:21
@vvasuki @jamadagni I just sent email to the sanskrit-programmers and grantha-lipi groups. The Sama Veda svara rendering is much better now in v0.5.0.
<img width="967" alt="Screenshot 2022-01-03 at 15 06 30" src="https://user-images.githubusercontent.com/5531915/147920028-1a20988d-c243-49e0-9732-71dd292c0ae3.png">
